### ISSUE TITLE
error when requiring package

### ISSUE THREAD

**Issue by ryan-lingle** [Matt-Jensen/lnrpc#19]
```javascript
const createLnrpc = require('lnrpc');
```

leads to the following error:
Uncaught TypeError: Cannot read property '_handle' of undefined

seems to be occurring in the grpc node_modules:
./node_modules/grpc/node_modules/set-blocking/index.js

**Comment by Matt-Jensen** [comment]
Not able to reproduce this.  Can you give me more info on your exact steps?
