### ISSUE TITLE
Bug: Can't find `rpc.proto`

### ISSUE THREAD

**Issue by gabmontes** [Matt-Jensen/lnrpc#23]
On a clean install of version 0.5.0 (using `npm`), `rpc.proto` can't be found as it is neither present in the package's root folder nor `lnd` is installed as a dependency.

Even if `lnd` is installed as dependency, version 0.0.2 (currently available in `npm`) is old and the provided `rpc.proto` will neither work.

A workaround would be to grab the file from GitHub or provide a configuration parameter to specify the path to the file.

**Comment by Matt-Jensen** [comment]
The `rpc.proto` file can be found in: `<my-project-root>/node_modules/lnrpc/node_modules/lnd/lnrpc` after you do an npm install.

Are you saying that this project ought to install `lnd` as a direct dependency of any project that uses it?

**Comment by AnthonyRonning** [comment]
Was having a bit of trouble with this myself. Reproduced in 2 ways: 

1. `npm install` a 2nd time seemed to remove `lnrpc/node_modules`
2. `NODE_ENV=production npm start` would remove it as well. 

Adding `lnrpc` as a `bundledDependency` in addition to a dependency stopped npm from removing it in case 1. However, I couldn't get it from getting removed in case 2. 

This was affecting lnrpc in my app being deployed to Heroku, so as a temporary measure I am leaving `NODE_ENV` in development mode for now - seems to be working. I'm not a javascript / npm pro so I'm not sure what to do from here but that's my insights.

**Comment by Matt-Jensen** [comment]
Seems related to: https://github.com/shama/napa/issues/81

**Comment by Matt-Jensen** [comment]
Just [wrote a potential fix here](https://github.com/Matt-Jensen/lnrpc/tree/hotfix/23-cache-rpc-proto) still needs testing, however I'd love any feedback you have.

**Comment by AnthonyRonning** [comment]
Thanks Matt! I can test it out later tonight.

**Comment by AnthonyRonning** [comment]
Worked for me! Deployed to Heroku in production mode and no issues. 

Thanks a lot!

**Comment by Matt-Jensen** [comment]
@AnthonyRonning Thanks for looking into that.  I'll get this shipped ASAP.
